# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            
tagline:          
description:      
url:              
baseurl:          /

author:
  name:           'FlowersAtDusk'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/flowersatdusk/flowersatdusk.github.io

# Gems
plugins: 	        [jekyll-paginate, jekyll-gist]
