# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            
tagline:          
description:      
url:              
baseurl:          /

url:              "https://flowersatdusk.github.io"

author:
  name:           

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/flowersatdusk

# Gems
plugins: 	        [jekyll-paginate, jekyll-gist]

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: flowersatdusk
