# Dependencies
# markdown:         redcarpetkramdown
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            flowersatdusk
tagline:          
description:      
url:              http://flowersatdusk.github.io
baseurl:          

author:
  name:           
  url:            
paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/flowersatdusk

# Plugins
plugins:          [jekyll-paginate, jekyll-gist]

# Disqus comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: flowersatdusk

# Google analytics
google_analytics: UA-105751783-1